import express from 'express';
import userRoutes from './userRoutes.js';
import clientRoutes from './clientRoutes.js';
import authRoutes from './authRoutes.js';
import instaRoutes from "./instaRoutes.js";
import quoteRoutes from './quoteRoutes.js';
import oauthRoutes from './oauthRoutes.js';
import tiktokRoutes from "./tiktokRoutes.js";
import aggregatorRoutes from "./aggregatorRoutes.js";
import metaRoutes from './metaRoutes.js';
import logRoutes from './logRoutes.js';
import linkReportRoutes from './linkReportRoutes.js';
import linkReportKhususRoutes from './linkReportKhususRoutes.js';
import amplifyRoutes from './amplifyRoutes.js';
import amplifyKhususRoutes from './amplifyKhususRoutes.js';
import editorialEventRoutes from './editorialEventRoutes.js';
import pressReleaseDetailRoutes from './pressReleaseDetailRoutes.js';
import premiumRequestRoutes from './premiumRequestRoutes.js';
import likesRoutes from './likesRoutes.js';
import userRolesRoutes from './userRolesRoutes.js';
import instagramRoutes from './instagramRoutes.js';

const router = express.Router();

router.use('/clients', clientRoutes);
router.use('/users', userRoutes);
router.use('/auth', authRoutes);
router.use("/insta", instaRoutes);
router.use("/instagram", instagramRoutes);
router.use("/tiktok", tiktokRoutes);
router.use("/aggregator", aggregatorRoutes);
router.use('/likes', likesRoutes);
router.use('/quotes', quoteRoutes);
router.use('/oauth', oauthRoutes);
router.use('/metadata', metaRoutes);
router.use('/logs', logRoutes);
router.use('/link-reports', linkReportRoutes);
router.use('/link-reports-khusus', linkReportKhususRoutes);
router.use('/events', editorialEventRoutes);
router.use('/press-release-details', pressReleaseDetailRoutes);
router.use('/amplify', amplifyRoutes);
router.use('/amplify-khusus', amplifyKhususRoutes);
router.use('/premium-requests', premiumRequestRoutes);
router.use('/user_roles', userRolesRoutes);
export default router;
